import { questions } from './data/questions.js';

export const state = {
  supa: null,
  currentUser: null,
  allQuestions: [],
  currentQuestions: [],
  currentMode: 'preview',
  activeModuleName: '',
  get activeQuestions() { return this._activeQuestions || questions; },
  set activeQuestions(v) { this._activeQuestions = v; },
  _activeQuestions: null,
  quizSelectionSummary: null,
  dashboardRefreshToken: 0,
  weakestRefreshToken: 0,
  lessonAccuracyRefreshToken: 0,
  appRenderToken: 0,
  friendDetailToken: 0,
  navRepeatLockTimer: null,
  dashboardSidebarCollapsed: false,
  selectedLessonTitle: '',
  friendsSearchQuery: '',
  friendsSelectedId: null,
  friendsState: null,
  profileOnboardingProfile: null,
  profileOnboardingSaving: false,
  dashboardPreloadCache: null,
  dashboardPreloadKey: '',
  quizMode: 'Stopwatch',
  timer: null,
  answered: {},
  quizSessionActive: false,
  quizSubmitting: false,
  quizElapsed: 0,
  activeQuizTitle: 'Principles of Flight Quiz',
  activeQuizMeta: 'Principles of Flight • Airflow',
  themeMode: localStorage.getItem('revitTheme') || 'light',
  surfaceAnimationFrame: 0,
  dailyTimer: null,
  dailyResetTimer: null,
  dailyState: null,
  dailyLocked: false,
  dailyPaused: false,
  dailyLeaderboardMode: 'school',
  dailyTaskHistoryCache: [],
  dailyTaskLoadedFor: null,
  dailyQuestionDeadline: 0,
  dailyPauseRemaining: 0,
  dailyAudioCtx: null,
  dailyLastTickSecond: null,
};
